filetype off
set shellslash
set rtp+=~/vimfiles/bundle/Vundle.vim
call vundle#begin('~/vimfiles/bundle')
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-eunuch'
Plugin 'yegappan/mru'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'altercation/vim-colors-solarized'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

source $VIMRUNTIME/vimrc_example.vim

set nocompatible
set enc=utf-8
set nobackup
set undodir=~\vimfiles\undodir
if !isdirectory(&undodir)
  call mkdir(&undodir, 'p', 0700)
endif

if has('mouse')
  if has('gui_running') || (&term =~ 'xterm' && !has('mac'))
    set mouse=a
  else
    set mouse=nvi
  endif
endif

set fileencodings=ucs-bom,utf-8,gb18030,latin1

if has('gui_running')
  set guifont=Courier_New:h16
endif

set scrolloff=1

let do_syntax_sel_menu = 1

let do_no_lazyload_menus = 1

if !has('gui_running')
  " 设置文本菜单
  if has('wildmenu')
    set wildmenu
    set cpoptions-=<
    set wildcharm=<C-Z>
    nnoremap <F10>      :emenu <C-Z>
    inoremap <F10> <C-O>:emenu <C-Z>
  endif
endif

" 如果目标文件已经打开，则把对应的标签页移到最前面
if v:version >= 800
  packadd! editexisting
endif

" 设置快捷键，分割窗口后快速切换窗口
nnoremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
nnoremap <C-S-Tab> <C-W>W
inoremap <C-S-Tab> <C-O><C-W>W

" 停止搜索高亮的键映射
nnoremap <silent> <F2> :nohlsearch<CR>
inoremap <silent> <F2> <C-O> :nohlsearch<CR>

" 一直显示行号
set number

" 设置主题以及修改背景色
syntax enable
set background=dark
colorscheme solarized

" 设置真彩色支持
set termguicolors

" 设置状态栏
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" 设置缩进为4个空格
set shiftwidth=4 softtabstop=4 expandtab

" 解决菜单中文乱码问题，一定要加在最后
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
